- name: Instalar paquete php-fpm
  apt:
    name:
      - php-fpm
      - php-mysql
      - php-cli
      - php-common
      - php-mbstring
    state: present
    update_cache: yes


- name: Copiar archivo www.conf
  ansible.builtin.copy:
    src: ../files/www.conf
    dest: /etc/php/8.4/fpm/pool.d/www.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart php8.4-fpm

- name: Crear DocumentRoot si no existe
  ansible.builtin.file:
    path: /{{item["datos"]["documentroot"]}}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items:
    - "{{virtualhosts}}"

- name: Copiar aplicación Guestbook
  ansible.builtin.copy:
    src: app/
    dest: "/{{ base_web_path }}/"
    owner: www-data
    group: www-data
    mode: '0644'
    directory_mode: '0755'
  
- name: Crear fichero de configuración config.php dentro de la aplicación
  ansible.builtin.template:
    src: config.php.j2
    dest: "/{{ base_web_path }}/config.php"
    owner: www-data
    group: www-data
